---
table: SQLSRV_migrations

databases:
    -
        name: SISMED
        server: 192.168.10.11
        username: SISMED
        password: Sismed.123
        port: 1433

sources:
    -
        name: sismed
        driver: DBF
        database: SISMED
        enabled: true
        path: \\192.168.13.24\Users\efloresp\Desktop\A\
